name: PR update

# on pull_request: #
on: [pull_request]

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update PR
        uses: maxkomarychev/pr-updater-action@v1.0.0
